from tkinter import *
from PIL import ImageTk,Image
import random
root = Tk()
root.geometry("1920x1080")
def hyd():
    la = Label(root,text="NAMASTE HYDERABAD\nNOW SHOWING \n")
    la.pack()
    rf = Frame(root,bg="red",borderwidth=6,relief=SUNKEN)
    rf.pack(side=LEFT,anchor="nw")
    tf = Frame(root,bg="blue",borderwidth=6,relief=SUNKEN)
    tf.pack(side=LEFT,anchor="nw")
    vf = Frame(root,bg="black",borderwidth=6,relief=SUNKEN)
    vf.pack(side=LEFT,anchor="nw")
    rb = Button(rf,image=photo,command = RRRT)
    rb.pack(side=LEFT,anchor="nw")
    vb = Button(vf,image=photo2,command=VIKT)
    vb.pack(side=LEFT,anchor="nw")
    tb = Button(tf,image=photo1,command=THOR)
    tb.pack(side=LEFT,anchor="nw")
    hf = Frame(root,bg="black",borderwidth=6,relief=SUNKEN)
    hf.pack(side=LEFT,anchor="nw")
    hb = Button(hf,image=photo3,command=BNT)
    hb.pack(side=LEFT,anchor="nw")
    af = Frame(root,bg="violet",borderwidth=6,relief=SUNKEN)
    af.pack(side=LEFT,anchor="nw")
    ab = Button(af,image=photo4,command=AVE)
    ab.pack(side=LEFT,anchor="nw")
def CHE():
    la = Label(root, text="VANAKKAM CHENNAI\nNOW SHOWING \n")
    la.pack()
    rf = Frame(root, bg="red", borderwidth=6, relief=SUNKEN)
    rf.pack(side=LEFT, anchor="nw")
    tf = Frame(root, bg="blue", borderwidth=6, relief=SUNKEN)
    tf.pack(side=LEFT, anchor="nw")
    vf = Frame(root, bg="black", borderwidth=6, relief=SUNKEN)
    vf.pack(side=LEFT, anchor="nw")
    rb = Button(rf, image=photo5,command=PUSHT)
    rb.pack(side=LEFT, anchor="nw")
    vb = Button(vf,image=photo6,command=VIKTA)
    vb.pack(side=LEFT, anchor="nw")
    tb = Button(tf,image=photo7,command=abc)
    tb.pack(side=LEFT, anchor="nw")
    hf = Frame(root, bg="black", borderwidth=6, relief=SUNKEN)
    hf.pack(side=LEFT, anchor="nw")
    hb = Button(hf,image = photo8,command=MAS)
    hb.pack(side=LEFT, anchor="nw")
    af = Frame(root, bg="violet", borderwidth=6, relief=SUNKEN)
    af.pack(side=LEFT, anchor="nw")
    ab = Button(af,image = photo9,command=MA)
    ab.pack(side=LEFT, anchor="nw")
def BAN():
    la = Label(root, text="SWAGATHA BANGLORE\nNOW SHOWING \n")
    la.pack()
    rf = Frame(root, bg="red", borderwidth=6, relief=SUNKEN)
    rf.pack(side=LEFT, anchor="nw")
    tf = Frame(root, bg="blue", borderwidth=6, relief=SUNKEN)
    tf.pack(side=LEFT, anchor="nw")
    vf = Frame(root, bg="black", borderwidth=6, relief=SUNKEN)
    vf.pack(side=LEFT, anchor="nw")
    rb = Button(rf, image=photo10,command=KGF)
    rb.pack(side=LEFT, anchor="nw")
    vb = Button(vf, image=photo11,command=VIKR)
    vb.pack(side=LEFT, anchor="nw")
    tb = Button(tf, image=photo12,command=AVEK)
    tb.pack(side=LEFT, anchor="nw")
    hf = Frame(root, bg="black", borderwidth=6, relief=SUNKEN)
    hf.pack(side=LEFT, anchor="nw")
    hb = Button(hf, image=photo13,command=THORK)
    hb.pack(side=LEFT, anchor="nw")
    af = Frame(root, bg="violet", borderwidth=6, relief=SUNKEN)
    af.pack(side=LEFT, anchor="nw")
    ab = Button(af, image=photo14,command=WAK)
    ab.pack(side=LEFT, anchor="nw")
def KGF():
    root1 = Tk()
    root1.title("KGF")
    root1.geometry("600x600")
    root1.configure(bg="black")
    rfr = Frame(root1, bg="red", borderwidth=5, relief=SUNKEN)
    rfr.pack()
    rla = Label(rfr, text="KGF(2-D)(KANNADA)\n RELEASING ON 17th DECEMBER 2022")
    rla1 = Label(root1,
                 text="SYNOPSIS:")
    rla1.pack()
    rla2 = Label(root1, text="NOW SHOWING IN")
    rla2.pack()
    rba = Button(root1, text="INOX-BANGLORE", bg="grey", fg="white", command=IB)
    rba.pack()
    rba1 = Button(root1, text="CINEPOLIS", bg="grey", fg="white", command=CIN)
    rba1.pack()
    rba2 = Button(root1, text="PVR-ORION", bg="grey", fg="white", command=PVO)
    rba2.pack()
    rla.pack()
    root1.mainloop()
def AVEK():
    root1 = Tk()
    root1.title("AVENGERS KANG DYNASTY")
    root1.geometry("600x600")
    root1.configure(bg="black")
    rfr = Frame(root1, bg="red", borderwidth=5, relief=SUNKEN)
    rfr.pack()
    rla = Label(rfr, text="AVENGERS KANG DYNASTY(2-D)(ENGLISH)\n RELEASING ON 17th DECEMBER 2022")
    rla1 = Label(root1,
                 text="SYNOPSIS:")
    rla1.pack()
    rla2 = Label(root1, text="NOW SHOWING IN")
    rla2.pack()
    rba = Button(root1, text="INOX-BANGLORE", bg="grey", fg="white", command=IB)
    rba.pack()
    rba1 = Button(root1, text="CINEPOLIS", bg="grey", fg="white", command=CIN)
    rba1.pack()
    rba2 = Button(root1, text="PVR-ORION", bg="grey", fg="white", command=PVO)
    rba2.pack()
    rla.pack()
    root1.mainloop()
def VIKR():
    root1 = Tk()
    root1.title("VIKR")
    root1.geometry("600x600")
    root1.configure(bg="black")
    rfr = Frame(root1, bg="red", borderwidth=5, relief=SUNKEN)
    rfr.pack()
    rla = Label(rfr, text="VIKRANT:RONA(2-D)(KANNADA)\n RELEASING ON 17th DECEMBER 2022")
    rla1 = Label(root1,
                 text="SYNOPSIS:")
    rla1.pack()
    rla2 = Label(root1, text="NOW SHOWING IN")
    rla2.pack()
    rba = Button(root1, text="INOX-BANGLORE", bg="grey", fg="white", command=IB)
    rba.pack()
    rba1 = Button(root1, text="CINEPOLIS", bg="grey", fg="white", command=CIN)
    rba1.pack()
    rba2 = Button(root1, text="PVR-ORION", bg="grey", fg="white", command=PVO)
    rba2.pack()
    rla.pack()
    root1.mainloop()
def THORK():
    root1 = Tk()
    root1.title("THOR")
    root1.geometry("600x600")
    root1.configure(bg="black")
    rfr = Frame(root1, bg="red", borderwidth=5, relief=SUNKEN)
    rfr.pack()
    rla = Label(rfr, text="THOR(2-D)(KANNADA)\n RELEASING ON 17th DECEMBER 2022")
    rla1 = Label(root1,
                 text="SYNOPSIS:")
    rla1.pack()
    rla2 = Label(root1, text="NOW SHOWING IN")
    rla2.pack()
    rba = Button(root1, text="INOX-BANGLORE", bg="grey", fg="white", command=IB)
    rba.pack()
    rba1 = Button(root1, text="CINEPOLIS", bg="grey", fg="white", command=CIN)
    rba1.pack()
    rba2 = Button(root1, text="PVR-ORION", bg="grey", fg="white", command=PVO)
    rba2.pack()
    rla.pack()
    root1.mainloop()
def WAK():
    root1 = Tk()
    root1.title("WAKANDA FOREVER")
    root1.geometry("600x600")
    root1.configure(bg="black")
    rfr = Frame(root1, bg="red", borderwidth=5, relief=SUNKEN)
    rfr.pack()
    rla = Label(rfr, text="BLACK-PANTHER:WAKANDA FOREVER(2-D)(ENGLISH)\n RELEASING ON 17th DECEMBER 2022")
    rla1 = Label(root1,
                 text="SYNOPSIS:")
    rla1.pack()
    rla2 = Label(root1, text="NOW SHOWING IN")
    rla2.pack()
    rba = Button(root1, text="INOX-BANGLORE", bg="grey", fg="white", command=IB)
    rba.pack()
    rba1 = Button(root1, text="CINEPOLIS", bg="grey", fg="white", command=CIN)
    rba1.pack()
    rba2 = Button(root1, text="PVR-ORION", bg="grey", fg="white", command=PVO)
    rba2.pack()
    rla.pack()
    root1.mainloop()
def IB():
    print("SELECTED INOX-BANGLORE")
    print("TICKET PRICE IS 195\-")
    q = int(input("NUMBER OF TICKETS = "))
    print("GST IS 18%")
    amt = q * 195
    tamt = (amt) * (18 / 100) + amt
    print("PAYMENT OPTIONS:1.CARD\n2.UPI\n")
    g = int(input())
    if (g == 1):
        print("ENTER CARD NO:")
        cno = int(input())
        print("ENTER CVV:")
        cvv = int(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print(" PAID AMOUNT ", tamt, q, "TICKET BOOKED  AT INOX-BANGLORE")
        else:
            print("PAYMENT FAILED")
    if (g == 2):
        print("ENTER UPI ID:")
        upi = str(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print("PAID AMOUNT ", tamt, q, "TICKET BOOKED  AT INOX-BANGLORE")
        else:
            print("PAYMENT FAILED")
def CIN():
    print("SELECTED CINEPOLIS")
    print("TICKET PRICE IS 195\-")
    q = int(input("NUMBER OF TICKETS = "))
    print("GST IS 18%")
    amt = q * 195
    tamt = (amt) * (18 / 100) + amt
    print("PAYMENT OPTIONS:1.CARD\n2.UPI\n")
    g = int(input())
    if (g == 1):
        print("ENTER CARD NO:")
        cno = int(input())
        print("ENTER CVV:")
        cvv = int(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print(" PAID AMOUNT ", tamt, q, "TICKET BOOKED  AT CINEPOLIS")
        else:
            print("PAYMENT FAILED")
    if (g == 2):
        print("ENTER UPI ID:")
        upi = str(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print("PAID AMOUNT ", tamt, q, "TICKET BOOKED  AT CINEPOLIS")
        else:
            print("PAYMENT FAILED")
def PVO():
    print("SELECTED PVR-ORION ")
    print("TICKET PRICE IS 195\-")
    q = int(input("NUMBER OF TICKETS = "))
    print("GST IS 18%")
    amt = q * 195
    tamt = (amt) * (18 / 100) + amt
    print("PAYMENT OPTIONS:1.CARD\n2.UPI\n")
    g = int(input())
    if (g == 1):
        print("ENTER CARD NO:")
        cno = int(input())
        print("ENTER CVV:")
        cvv = int(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print(" PAID AMOUNT ", tamt, q, "TICKET BOOKED  AT PVR-ORION")
        else:
            print("PAYMENT FAILED")
    if (g == 2):
        print("ENTER UPI ID:")
        upi = str(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print("PAID AMOUNT ", tamt, q, "TICKET BOOKED  AT PVR-ORION")
        else:
            print("PAYMENT FAILED")
def PUSHT():
    root1 = Tk()
    root1.title("PUSHPA")
    root1.geometry("600x600")
    root1.configure(bg="black")
    rfr = Frame(root1, bg="red", borderwidth=5, relief=SUNKEN)
    rfr.pack()
    rla = Label(rfr, text="PUSHPA(2-D)(TAMIL)\n RELEASING ON 17th DECEMBER 2022")
    rla1 = Label(root1,
                 text="SYNOPSIS:")
    rla1.pack()
    rla2 = Label(root1, text="NOW SHOWING IN")
    rla2.pack()
    rba = Button(root1, text="1.CASINO CINEMA HALL", bg="grey", fg="white", command=CCH)
    rba.pack()
    rba1 = Button(root1, text="UDHAYAM THEATRE", bg="grey", fg="white", command=UT)
    rba1.pack()
    rba2 = Button(root1, text="KASI THEATRE", bg="grey", fg="white", command=KT)
    rba2.pack()
    rla.pack()
    root1.mainloop()
def VIKTA():
    root1 = Tk()
    root1.title("2.0")
    root1.geometry("600x600")
    root1.configure(bg="black")
    rfr = Frame(root1, bg="red", borderwidth=5, relief=SUNKEN)
    rfr.pack()
    rla = Label(rfr, text="2.0(2-D)(TAMIL)\n RELEASING ON 17th DECEMBER 2022")
    rla1 = Label(root1,
                 text="SYNOPSIS:")
    rla1.pack()
    rla2 = Label(root1, text="NOW SHOWING IN")
    rla2.pack()
    rba = Button(root1, text="1.CASINO CINEMA HALL", bg="grey", fg="white", command=CCH)
    rba.pack()
    rba1 = Button(root1, text="UDHAYAM THEATRE", bg="grey", fg="white", command=UT)
    rba1.pack()
    rba2 = Button(root1, text="KASI THEATRE", bg="grey", fg="white", command=KT)
    rba2.pack()
    rla.pack()
    root1.mainloop()
def abc():
    root1 = Tk()
    root1.title("VIKRAM")
    root1.geometry("600x600")
    root1.configure(bg="black")
    rfr = Frame(root1, bg="red", borderwidth=5, relief=SUNKEN)
    rfr.pack()
    rla = Label(rfr, text="VIKRAM(2-D)(TAMIL)\n RELEASING ON 17th DECEMBER 2022")
    rla1 = Label(root1,
                 text="SYNOPSIS:")
    rla1.pack()
    rla2 = Label(root1, text="NOW SHOWING IN")
    rla2.pack()
    rba = Button(root1, text="1.CASINO CINEMA HALL", bg="grey", fg="white", command=CCH)
    rba.pack()
    rba1 = Button(root1, text="UDHAYAM THEATRE", bg="grey", fg="white", command=UT)
    rba1.pack()
    rba2 = Button(root1, text="KASI THEATRE", bg="grey", fg="white", command=KT)
    rba2.pack()
    rla.pack()
    root1.mainloop()
def MA():
    root1 = Tk()
    root1.title("MAHAAN")
    root1.geometry("600x600")
    root1.configure(bg="black")
    rfr = Frame(root1, bg="red", borderwidth=5, relief=SUNKEN)
    rfr.pack()
    rla = Label(rfr, text="MAHAAN(2-D)(TAMIL)\n RELEASING ON 17th DECEMBER 2022")
    rla1 = Label(root1,
                 text="SYNOPSIS:")
    rla1.pack()
    rla2 = Label(root1, text="NOW SHOWING IN")
    rla2.pack()
    rba = Button(root1, text="1.CASINO CINEMA HALL", bg="grey", fg="white", command=CCH)
    rba.pack()
    rba1 = Button(root1, text="UDHAYAM THEATRE", bg="grey", fg="white", command=UT)
    rba1.pack()
    rba2 = Button(root1, text="KASI THEATRE", bg="grey", fg="white", command=KT)
    rba2.pack()
    rla.pack()
    root1.mainloop()
def MAS():
    root1 = Tk()
    root1.title("MASTER")
    root1.geometry("600x600")
    root1.configure(bg="black")
    rfr = Frame(root1, bg="red", borderwidth=5, relief=SUNKEN)
    rfr.pack()
    rla = Label(rfr, text="MASTER(2-D)(TAMIL)\n RELEASING ON 17th DECEMBER 2022")
    rla1 = Label(root1,
                 text="SYNOPSIS:")
    rla1.pack()
    rla2 = Label(root1, text="NOW SHOWING IN")
    rla2.pack()
    rba = Button(root1, text="1.CASINO CINEMA HALL", bg="grey", fg="white", command=CCH)
    rba.pack()
    rba1 = Button(root1, text="UDHAYAM THEATRE", bg="grey", fg="white", command=UT)
    rba1.pack()
    rba2 = Button(root1, text="KASI THEATRE", bg="grey", fg="white", command=KT)
    rba2.pack()
    rla.pack()
    root1.mainloop()




def CCH():
    print("SELECTED CASINO CINEMA HALL")
    print("TICKET PRICE IS 195\-")
    q = int(input("NUMBER OF TICKETS = "))
    print("GST IS 18%")
    amt = q * 195
    tamt = (amt) * (18 / 100) + amt
    print("PAYMENT OPTIONS:1.CARD\n2.UPI\n")
    g = int(input())
    if (g == 1):
        print("ENTER CARD NO:")
        cno = int(input())
        print("ENTER CVV:")
        cvv = int(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print(" PAID AMOUNT ", tamt, q, "TICKET BOOKED  AT CASINO CINEMA HALL")
        else:
            print("PAYMENT FAILED")
    if (g == 2):
        print("ENTER UPI ID:")
        upi = str(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print("PAID AMOUNT ", tamt, q, "TICKET BOOKED  AT CASINO CINEMA HALL")
        else:
            print("PAYMENT FAILED")
def UT():
    print("SELECTED UDHAYAM THEATRE")
    print("TICKET PRICE IS 195\-")
    q = int(input("NUMBER OF TICKETS = "))
    print("GST IS 18%")
    amt = q * 195
    tamt = (amt) * (18 / 100) + amt
    print("PAYMENT OPTIONS:1.CARD\n2.UPI\n")
    g = int(input())
    if (g == 1):
        print("ENTER CARD NO:")
        cno = int(input())
        print("ENTER CVV:")
        cvv = int(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print(" PAID AMOUNT ", tamt, q, "TICKET BOOKED  AT UDHAYAM THEATRE")
        else:
            print("PAYMENT FAILED")
    if (g == 2):
        print("ENTER UPI ID:")
        upi = str(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print("PAID AMOUNT ", tamt, q, "TICKET BOOKED  AT UDHAYAM THEATRE")
        else:
            print("PAYMENT FAILED")
def KT():
    print("SELECTED KASI THEATRE")
    print("TICKET PRICE IS 195\-")
    q = int(input("NUMBER OF TICKETS = "))
    print("GST IS 18%")
    amt = q * 195
    tamt = (amt) * (18 / 100) + amt
    print("PAYMENT OPTIONS:1.CARD\n2.UPI\n")
    g = int(input())
    if (g == 1):
        print("ENTER CARD NO:")
        cno = int(input())
        print("ENTER CVV:")
        cvv = int(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print(" PAID AMOUNT ", tamt, q, "TICKET BOOKED  AT KASI THEATRE")
        else:
            print("PAYMENT FAILED")
    if (g == 2):
        print("ENTER UPI ID:")
        upi = str(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print("PAID AMOUNT ", tamt, q, "TICKET BOOKED  AT KASI THEATRE")
        else:
            print("PAYMENT FAILED")




def RRRT():
    root1 = Tk()
    root1.title("RRR")
    root1.geometry("600x600")
    root1.configure(bg = "black")
    rfr = Frame(root1,bg="red",borderwidth=5,relief = SUNKEN)
    rfr.pack()
    rla = Label(rfr,text="RRR(2-D)(TELUGU)\n RELEASING ON 25th MARCH 2022")
    rla1 = Label(root1,text = "SYNOPSIS:A fictitious story about two legendary revolutionaries and their journey away from home before they started fighting for their country in 1920s.")
    rla1.pack()
    rla2 =  Label(root1,text="NOW SHOWING IN")
    rla2.pack()
    rba = Button(root1,text="1.ASIAN M-CUBE MALL:ATTAPUR",bg="grey",fg="white",command=AMA)
    rba.pack()
    rba1 = Button(root1,text="2.GVK-ONE:BANJARA HILLS",bg="grey",fg="white",command=GVA)
    rba1.pack()
    rba2 = Button(root1, text="3.PVR:MADHAPUR", bg="grey", fg="white",command=PVA)
    rba2.pack()
    rla.pack()
    root1.mainloop()
def THOR():
    root2 = Tk()
    root2.title("THOR:LOVE&THUNDER")
    root2.geometry("600x600")
    root2.configure(bg="black")
    rtr = Frame(root2, bg="red", borderwidth=5, relief=SUNKEN)
    rtr.pack()
    tla = Label(rtr, text="THOR:LOVE&THUNDER(2-D)(ENGLISH)\n RELEASING ON 7th MAY 2022")
    tla1 = Label(root2,text="SYNOPSIS:Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct.")
    tla1.pack()
    tla2 = Label(root2, text="NOW SHOWING IN")
    tla2.pack()
    tba = Button(root2, text="1.ASIAN M-CUBE MALL:ATTAPUR", bg="grey", fg="white", command=AMA)
    tba.pack()
    tba1 = Button(root2, text="2.GVK-ONE:BANJARA HILLS", bg="grey", fg="white", command=GVA)
    tba1.pack()
    tba2 = Button(root2, text="3.PVR:MADHAPUR", bg="grey", fg="white", command=PVA)
    tba2.pack()
    tla.pack()
    root2.mainloop()
def VIKT():
    root3 = Tk()
    root3.title("VIKRAM:TELUGU")
    root3.geometry("600x600")
    root3.configure(bg="black")
    rvr = Frame(root3, bg="red", borderwidth=5, relief=SUNKEN)
    rvr.pack()
    tla = Label(rvr, text="VIKRAM(2-D)(TELUGU)\n RELEASING ON 11th MAY 2022")
    tla1 = Label(root3,
                 text="SYNOPSIS:A high-octane action film where a special investigator is assigned a case of serial Killings. As the investigation proceeds, he finds the case is not what it seems to be and leading down this path is only going to end in a war between everyone involved.")
    tla1.pack()
    tla2 = Label(root3, text="NOW SHOWING IN")
    tla2.pack()
    tba = Button(root3, text="1.ASIAN M-CUBE MALL:ATTAPUR", bg="grey", fg="white", command=AMA)
    tba.pack()
    tba1 = Button(root3, text="2.GVK-ONE:BANJARA HILLS", bg="grey", fg="white", command=GVA)
    tba1.pack()
    tba2 = Button(root3, text="3.PVR:MADHAPUR", bg="grey", fg="white", command=PVA)
    tba2.pack()
    tla.pack()
    root3.mainloop()
def BNT():
    root4 = Tk()
    root4.title("BHEEMLA NAYAK")
    root4.geometry("600x600")
    root4.configure(bg="black")
    rvr = Frame(root4, bg="red", borderwidth=5, relief=SUNKEN)
    rvr.pack()
    tla = Label(rvr, text="BHEEMLA NAYAK(2-D)(TELUGU)\n RELEASING ON 25th FEB 2022")
    tla1 = Label(root4,
                 text="SYNOPSIS:")
    tla1.pack()
    tla2 = Label(root4, text="NOW SHOWING IN")
    tla2.pack()
    tba = Button(root4, text="1.ASIAN M-CUBE MALL:ATTAPUR", bg="grey", fg="white", command=AMA)
    tba.pack()
    tba1 = Button(root4, text="2.GVK-ONE:BANJARA HILLS", bg="grey", fg="white", command=GVA)
    tba1.pack()
    tba2 = Button(root4, text="3.PVR:MADHAPUR", bg="grey", fg="white", command=PVA)
    tba2.pack()
    tla.pack()
    root4.mainloop()
def AVE():
    root5 = Tk()
    root5.title("AVENGERS:KANG DYNASTY")
    root5.geometry("600x600")
    root5.configure(bg="black")
    rvr = Frame(root5, bg="red", borderwidth=5, relief=SUNKEN)
    rvr.pack()
    tla = Label(rvr, text="AVENGERS:KANG DYNASTY(2-D)(ENGLISH)\n RELEASING ON 25th NOV 2024")
    tla1 = Label(root5,
                 text="SYNOPSIS:")
    tla1.pack()
    tla2 = Label(root5, text="NOW SHOWING IN")
    tla2.pack()
    tba = Button(root5, text="1.ASIAN M-CUBE MALL:ATTAPUR", bg="grey", fg="white", command=AMA)
    tba.pack()
    tba1 = Button(root5, text="2.GVK-ONE:BANJARA HILLS", bg="grey", fg="white", command=GVA)
    tba1.pack()
    tba2 = Button(root5, text="3.PVR:MADHAPUR", bg="grey", fg="white", command=PVA)
    tba2.pack()
    tla.pack()
    root5.mainloop()




def AMA():
    print("SELECTED ASIAN-MCUBE")
    print("TICKET PRICE IS 195\-")
    q = int(input("NUMBER OF TICKETS = "))
    print("GST IS 18%")
    amt = q*195
    tamt = (amt)*(18/100)+amt
    print("PAYMENT OPTIONS:1.CARD\n2.UPI\n")
    g = int(input())
    if (g == 1):
        print("ENTER CARD NO:")
        cno = int(input())
        print("ENTER CVV:")
        cvv = int(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print(" PAID AMOUNT ",tamt,q,"TICKET BOOKED  AT ASIAN-MCUBE" )
        else:
            print("PAYMENT FAILED")
    if (g == 2):
        print("ENTER UPI ID:")
        upi = str(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print("PAID AMOUNT ",tamt,q,"TICKET BOOKED  AT ASIAN-MCUBE")
        else:
            print("PAYMENT FAILED")
def GVA():
    print("SELECTED GVK-ONE")
    print("TICKET PRICE IS 195\-")
    q = int(input("NUMBER OF TICKETS = "))
    print("GST IS 18%")
    amt = q * 195
    tamt = (amt) * (18 / 100) + amt
    print("PAYMENT OPTIONS:1.CARD\n2.UPI\n")
    g = int(input())
    if (g == 1):
        print("ENTER CARD NO:")
        cno = int(input())
        print("ENTER CVV:")
        cvv = int(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print("PAID AMOUNT ",tamt,q,"TICKET BOOKED  AT GVK-ONE")
        else:
            print("PAYMENT FAILED")
    if (g == 2):
        print("ENTER UPI ID:")
        upi = str(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP"))
        if (otp == user):
            print("PAID AMOUNT ",tamt,q,"TICKET BOOKED  AT GVK-ONE")
        else:
            print("PAYMENT FAILED")
def PVA():
    print("SELECTED PVR-HITECH")
    print("TICKET PRICE IS 195\-")
    q = int(input("NUMBER OF TICKETS = "))
    print("GST IS 18%")
    amt = q * 195
    tamt = (amt) * (18 / 100) + amt
    print("PAYMENT OPTIONS:1.CARD\n2.UPI\n")
    g = int(input())
    if (g == 1):
        print("ENTER CARD NO:")
        cno = int(input())
        print("ENTER CVV:")
        cvv = int(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP:"))
        if (otp == user):
            print("PAID AMOUNT ",tamt,q,"TICKET BOOKED  AT PVR-HITECH")
        else:
            print("PAYMENT FAILED")
    if (g == 2):
        print("ENTER UPI ID:")
        upi = str(input())
        otp = random.randrange(100000, 1000000)
        print("otp is", otp)
        user = int(input("ENTER OTP"))
        if (otp == user):
            print("PAID AMOUNT ",tamt,q,"TICKET BOOKED  AT PVR-HITECH")
        else:
            print("PAYMENT FAILED")


root.title("CINEMAA")
f1 = Frame(root,bg="red",borderwidth=6,relief=SUNKEN)
f1.pack(side = TOP,fill="x")
l = Label(f1,text="WELCOME TO CINEMAA",bg="white",fg="red",font="bold")
f2 = Frame(root,bg="red",borderwidth=6,relief=SUNKEN)
f2.pack(side = LEFT,anchor="nw")
l1 = Label(f2,text="Please choose your city",bg="grey",fg="white",font="bold")
l1.pack()
l.pack(padx=100)
b = Button(f2,text = "HYDERABAD",bg="white",fg="black",command = hyd)
b.pack()
b1 =  Button(f2,text = "CHENNAI",bg="white",fg="black",command=CHE)
b1.pack()
b2 =  Button(f2,text = "BANGLORE",bg="white",fg="black",command=BAN)
b2.pack()
image = Image.open("RRR.jpg")
photo = ImageTk.PhotoImage(image)
image1 = Image.open("THOR1.jpg")
photo1 = ImageTk.PhotoImage(image1)
image2 = Image.open("VIKRAM.jpg")
photo2 = ImageTk.PhotoImage(image2)
image3 = Image.open("HHVM.jpg")
photo3 = ImageTk.PhotoImage(image3)
image4 = Image.open("AV.jpg")
photo4 = ImageTk.PhotoImage(image4)
image5 = Image.open("PUSHPA.jpg")
photo5 = ImageTk.PhotoImage(image5)
image6 = Image.open("2.0.jpg")
photo6 = ImageTk.PhotoImage(image6)
image7 = Image.open("VIKRAM1.jpg")
photo7 = ImageTk.PhotoImage(image7)
image8 = Image.open("MASTER.jpg")
photo8 = ImageTk.PhotoImage(image8)
image9 = Image.open("MAHHAN.jpg")
photo9 = ImageTk.PhotoImage(image9)
image10 = Image.open("KGF.jpg")
photo10 = ImageTk.PhotoImage(image10)
image11 = Image.open("VIKRANT.jpg")
photo11 = ImageTk.PhotoImage(image11)
image12 = Image.open("AV.jpg")
photo12 = ImageTk.PhotoImage(image12)
image13 = Image.open("THOR1.jpg")
photo13 = ImageTk.PhotoImage(image13)
image14 = Image.open("WAKANDA.jpg")
photo14 = ImageTk.PhotoImage(image14)
root.mainloop()
